export const Get_Error="Get_Error"
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES "
export const GET_ALL_PRODUCTS="GET_ALL_PRODUCTS";
export const GET_SPECIFIC_PRODUCT="GET_SPECIFIC_PRODUCT"
export const GET_ALL_PRODUCTS_BY_CATEGORY="GET_ALL_PRODUCTS_BY_CATEGORY"